target 'ParallaxBlur', :exclusive => true do
    
    pod "ParallaxBlur", :path => "../"
    
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
    
end

target 'Tests', :exclusive => true do
    
    pod "ParallaxBlur", :path => "../"
    
    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
    
end
